<a href="https://colab.research.google.com/github/rgv-data-miners/MLP_Demo/blob/main/mlp_demo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [ ]:
K=32
eq2 = torch.nn.Linear(in_features=2,out_features=K)
eq4 = torch.nn.Linear(in_features=K,out_features=2)
eq3 = torch.nn.ReLU()


In [ ]:
x= torch.rand((100,2))

In [ ]:
#Eq 2
x = eq2(x)
x = eq3(x)
x = eq4(x)
output = torch.nn.functional.softmax(x)

<ipython-input-14-289de1c7af49>:5: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  output = torch.nn.functional.softmax(x)


In [ ]:
output

tensor([[0.4278, 0.5722],
        [0.4278, 0.5722],
        [0.4282, 0.5718],
        [0.4320, 0.5680],
        [0.4319, 0.5681],
        [0.4314, 0.5686],
        [0.4278, 0.5722],
        [0.4278, 0.5722],
        [0.4342, 0.5658],
        [0.4289, 0.5711],
        [0.4299, 0.5701],
        [0.4272, 0.5728],
        [0.4271, 0.5729],
        [0.4289, 0.5711],
        [0.4337, 0.5663],
        [0.4313, 0.5687],
        [0.4336, 0.5664],
        [0.4346, 0.5654],
        [0.4278, 0.5722],
        [0.4277, 0.5723],
        [0.4294, 0.5706],
        [0.4283, 0.5717],
        [0.4302, 0.5698],
        [0.4276, 0.5724],
        [0.4274, 0.5726],
        [0.4292, 0.5708],
        [0.4306, 0.5694],
        [0.4286, 0.5714],
        [0.4296, 0.5704],
        [0.4351, 0.5649],
        [0.4303, 0.5697],
        [0.4274, 0.5726],
        [0.4272, 0.5728],
        [0.4282, 0.5718],
        [0.4283, 0.5717],
        [0.4307, 0.5693],
        [0.4330, 0.5670],
        [0.4292, 0.5708],
        [0.4

In [ ]:
loss_func = torch.nn.CrossEntropyLoss()

label = torch.cat((torch.zeros(50,1),torch.ones(50,1))).squeeze().long()



In [ ]:
loss_func(output,label)

tensor(0.6955, grad_fn=<NllLossBackward0>)

In [ ]:
import torch.nn as nn

class MLP(nn.Module):
  def __init__(self, K):
    super(MLP,self).__init__()
    self.K = K
    self.eq2 = torch.nn.Linear(in_features=2,out_features=K)
    self.eq4 = torch.nn.Linear(in_features=K,out_features=2)
    self.eq3 = torch.nn.ReLU()
  def forward(self,x):
    x = self.eq2(x)
    x = self.eq3(x)
    x = self.eq4(x)
    y = torch.nn.functional.softmax(x)
    return y

model = MLP(64)




In [ ]:
import torch.optim as optim

optimizer = optim.SGD(model.parameters(), lr=0.01)

for i in range(10000):
  optimizer.zero_grad()
  o = model(x)
  l = loss_func(o,label)
  l.backward()
  optimizer.step()
  print(l)





<ipython-input-79-4d774deb85ea>:14: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  y = torch.nn.functional.softmax(x)


Streaming output truncated to the last 5000 lines.
tensor(0.6863, grad_fn=<NllLossBackward0>)
tensor(0.6863, grad_fn=<NllLossBackward0>)
tensor(0.6863, grad_fn=<NllLossBackward0>)
tensor(0.6863, grad_fn=<NllLossBackward0>)
tensor(0.6863, grad_fn=<NllLossBackward0>)
tensor(0.6863, grad_fn=<NllLossBackward0>)
tensor(0.6863, grad_fn=<NllLossBackward0>)
tensor(0.6863, grad_fn=<NllLossBackward0>)
tensor(0.6863, grad_fn=<NllLossBackward0>)
tensor(0.6863, grad_fn=<NllLossBackward0>)
tensor(0.6863, grad_fn=<NllLossBackward0>)
tensor(0.6863, grad_fn=<NllLossBackward0>)
tensor(0.6863, grad_fn=<NllLossBackward0>)
tensor(0.6863, grad_fn=<NllLossBackward0>)
tensor(0.6863, grad_fn=<NllLossBackward0>)
tensor(0.6863, grad_fn=<NllLossBackward0>)
tensor(0.6863, grad_fn=<NllLossBackward0>)
tensor(0.6863, grad_fn=<NllLossBackward0>)
tensor(0.6863, grad_fn=<NllLossBackward0>)
tensor(0.6863, grad_fn=<NllLossBackward0>)
tensor(0.6863, grad_fn=<NllLossBackward0>)
tensor(0.6863, grad_fn=<NllLossBackward0>)
ten

KeyboardInterrupt: ignored

In [ ]:
l.backward()

In [ ]:
optimizer.step()

In [ ]:
model.eq4.weight.grad

tensor([[-7.6351e-04, -8.0056e-06,  0.0000e+00, -1.0665e-04,  7.6424e-04,
         -1.5481e-03, -2.5534e-04,  0.0000e+00, -3.1304e-05,  3.8464e-06,
          0.0000e+00,  3.0977e-03,  1.6938e-03,  6.1190e-04, -6.1724e-05,
         -4.2841e-06,  1.3732e-04,  0.0000e+00, -1.0931e-04, -6.0061e-04,
          4.1924e-04, -1.6418e-03,  4.8047e-05, -7.4719e-04, -2.5935e-05,
         -8.9549e-05, -1.0112e-04,  0.0000e+00,  3.2070e-04,  2.3153e-06,
         -8.8528e-05, -1.2002e-04, -7.4726e-05,  3.1927e-04,  2.9729e-03,
         -1.4259e-04, -8.6624e-05,  7.8976e-07,  0.0000e+00,  0.0000e+00,
          1.4063e-04,  3.0985e-04, -1.0446e-04, -1.3483e-04,  0.0000e+00,
          0.0000e+00, -4.4968e-05, -3.1684e-06, -6.3553e-05,  4.9870e-04,
         -8.8483e-05,  2.4979e-04,  0.0000e+00,  0.0000e+00, -1.0306e-03,
         -5.0386e-05, -1.2746e-04, -5.4205e-04, -2.0686e-04,  0.0000e+00,
         -1.5470e-04,  3.7187e-04,  0.0000e+00,  4.9541e-04],
        [ 7.6351e-04,  8.0056e-06,  0.0000e+00,  1

In [ ]:
model.eq2.weight.grad

tensor([[ 2.9126e-04,  5.0866e-04],
        [ 6.9558e-08, -1.9529e-07],
        [ 0.0000e+00,  0.0000e+00],
        [ 8.9547e-07, -2.5216e-06],
        [ 2.6700e-04, -2.6031e-04],
        [ 4.8935e-04,  8.4458e-04],
        [ 5.1475e-05, -1.7731e-05],
        [ 0.0000e+00,  0.0000e+00],
        [-2.2173e-05,  4.6804e-06],
        [ 2.2197e-05,  4.5445e-06],
        [ 0.0000e+00,  0.0000e+00],
        [ 1.3514e-03, -1.5012e-03],
        [-5.2403e-05, -9.4221e-04],
        [-2.4310e-04,  6.5666e-06],
        [-1.9181e-05, -3.9305e-05],
        [-1.6764e-06,  4.7125e-06],
        [-1.1457e-04,  2.3891e-05],
        [ 0.0000e+00,  0.0000e+00],
        [ 3.8831e-04, -5.5085e-04],
        [-1.9924e-04, -5.5063e-05],
        [ 5.6594e-05,  9.2011e-05],
        [ 6.7636e-04,  4.3091e-04],
        [ 2.5642e-04, -1.1841e-04],
        [ 2.8791e-04,  6.6790e-04],
        [-1.3625e-06,  3.8398e-06],
        [ 3.0850e-07, -8.6683e-07],
        [-1.1356e-07,  3.1956e-07],
        [ 0.0000e+00,  0.000

In [ ]:
loss

tensor(0.6938, grad_fn=<NllLossBackward0>)